In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
corpus = ['I loved Crow', 'I hated Crow', 'Crow is a good bird', 'Its black and Dirty', 'Black is a Good Color.']

In [ ]:
vectorizer = CountVectorizer(analyzer = "word", 
                             lowercase=True, 
                             tokenizer = None, 
                             preprocessor = None, 
                             stop_words = None, 
                             max_features = 5000,
                             token_pattern='[a-zA-Z0-9$&+,:;=?@#|<>^*()%!-]+')

In [ ]:
wm = vectorizer.fit_transform(corpus)
print(wm.todense())

[[0 0 0 0 0 1 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 0 1 1 0 0 0]
 [1 0 1 0 0 1 0 1 0 0 1 0 0]
 [0 1 0 1 0 0 1 0 0 0 0 1 0]
 [1 0 0 1 1 0 0 1 0 0 1 0 0]]

In [ ]:
print(wm.shape)

(5, 13)

In [ ]:
vocabulary = vectorizer.vocabulary_
print(vocabulary)

{'i': 9, 'loved': 12, 'crow': 5, 'hated': 8, 'is': 10, 'a': 0, 'good': 7, 'bird': 2, 'its': 11, 'black': 3, 'and': 1, 'dirty': 6, 'color': 4}

In [ ]:
tokens = vectorizer.get_feature_names_out()
print(tokens)

['a' 'and' 'bird' 'black' 'color' 'crow' 'dirty' 'good' 'hated' 'i' 'is'
 'its' 'loved']

In [ ]:
doc_names = ['Doc{:d}'.format(idx) for idx, _ in enumerate(wm)]
df = pd.DataFrame(data=wm.toarray(), index=doc_names,
                  columns=tokens)

In [ ]:
df

      a  and  bird  black  color  crow  dirty  good  hated  i  is  its  loved
Doc0  0    0     0      0      0     1      0     0      0  1   0    0      1
Doc1  0    0     0      0      0     1      0     0      1  1   0    0      0
Doc2  1    0     1      0      0     1      0     1      0  0   1    0      0
Doc3  0    1     0      1      0     0      1     0      0  0   0    1      0
Doc4  1    0     0      1      1     0      0     1      0  0   1    0      0

In [ ]:
df['class'] = ['+', '-', '+', '-','+']
df[df['class'] == '+']

,a,and,bird,black,color,crow,dirty,good,hated,i,is,its,loved,class
Doc0,0,0,0,0,0,1,0,0,0,1,0,0,1,+
Doc2,1,0,1,0,0,1,0,1,0,0,1,0,0,+
Doc4,1,0,0,1,1,0,0,1,0,0,1,0,0,+

In [ ]:
df[df['class'] == '-']

,a,and,bird,black,color,crow,dirty,good,hated,i,is,its,loved,class
Doc1,0,0,0,0,0,1,0,0,1,1,0,0,0,-
Doc3,0,1,0,1,0,0,1,0,0,0,0,1,0,-